name: deploy

on:
  push:
    branches: [main, alpha]
  pull_request:
    branches: [main, alpha]

env:
  DOCKER_IMAGE: BE
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./BE/package-lock.json

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install dependencies
        working-directory: ./BE
        run: npm ci

      - name: Run tests
        working-directory: ./BE
        run: npm test
        env:
          CI: true

      - name: Run linter
        working-directory: ./BE
        run: npm run lint

      - name: Build application
        working-directory: ./BE
        run: npm run build

      - name: Build and Push Docker Image
        working-directory: ./BE
        env:
          NCP_ACCESS_KEY: ${{ secrets.NCP_ACCESS_KEY }}
          NCP_SECRET_KEY: ${{ secrets.NCP_SECRET_KEY }}
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
          docker tag ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} ${{ env.DOCKER_IMAGE }}:latest

          docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          docker push ${{ env.DOCKER_IMAGE }}:latest

      - name: Deploy to NCP Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_SERVER_HOST }}
          username: ${{ secrets.NCP_SERVER_USERNAME }}
          key: ${{ secrets.NCP_SERVER_SSH_KEY }}
          script: |
            docker pull ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
            docker stop my-app || true
            docker rm my-app || true
            docker run -d \
              --name my-app \
              -p 8080:8080 \
              ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
